export const GAME_LOOP_RENDER_RATE = 20;
export const GAME_BG_SPRITE_SIZE = 100;
export const GAME_MAX_VEHICLES_PER_LANE = 2;
export const GAME_VEHICLE_SPEED = 55;
export const GAME_HERO_SPEED = 45;
export const GAME_MAX_CRYSTALS = 10;
export const GAME_CRYSTAL_ROTATION_STEP = 20;
export const GAME_CRYSTAL_MAX_ANIMATION_LATENCY = 10;
