name: Deploy Ya Cloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: install modules
        run: /home/nkoroid/.nvm/versions/node/v16.15.1/npm install 
      - name: build and start up containers
        run: /home/nkoroid/.nvm/versions/node/v16.15.1/npm run start
      - name: clear unused containers
        run: docker image prune -f
